apiVersion: v1
kind: Service
metadata:
  name: {{ include "snowalert.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "snowalert.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webui.service.type }}
  ports:
    - port: {{ .Values.webui.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "snowalert.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
