apiVersion: v1
kind: Service
metadata:
  name: {{ include "snowalert.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.webui.service.annotations }}
  annotations: {{ toYaml .Values.webui.service.annotations | nindent 4 }}
{{- end }}
  labels:
    {{ include "snowalert.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webui.service.type }}
  ports:
    - port: {{ .Values.webui.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "snowalert.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
